version: "3.9"

services:
  java-app:
    image: amazoncorretto:8
    ports:
      - "8080:8080"
    volumes:
      - ./target/:/app
    entrypoint: sh -c "java -jar /app/projects-management-spring-boot-api-0.0.1-SNAPSHOT.jar"
    depends_on:
      db:
        condition: service_healthy

  pma:
    image: omar391/lamp:latest
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD:
      MAX_EXECUTION_TIME: 2000
    ports:
      - "8181:443"
    depends_on:
      db:
        condition: service_healthy

  db:
    platform: linux/amd64
    image: bitnami/mysql:5.7.37
    ports:
      - "3306:3306"
    expose:
      - 3306
    volumes:
      - mysql_data:/bitnami/mysql/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root"]
      timeout: 20s
      retries: 10

volumes:
  mysql_data:
